const products = [
  {
    name: "Classic Black Hoodie",
    details: "A comfortable, all-season hoodie made from premium cotton blend. Minimalist design for street or casual wear.",
    ratings: 4.6,
    price: 1299,
    discountType : "percentage",
    discountValue: 20,
    images: [{url : "https://th.bing.com/th/id/OIP.ZTdNVuWqsPRXVV_kr8kqWAHaI4?w=208&h=249&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "fashion",
  },
  {
    name: "Wireless Noise-Cancelling Headphones",
    details: "Experience crystal-clear sound with active noise cancellation and 40-hour battery life. Includes travel pouch.",
    ratings: 4.8,
    price: 4999,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://plus.unsplash.com/premium_photo-1679513691474-73102089c117?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aGVhZHBob25lc3xlbnwwfHwwfHx8MA%3D%3D"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "electronics",
  },
  {
    name: "Stainless Steel Water Bottle",
    details: "750ml insulated bottle. Keeps drinks cold for 24 hrs, hot for 12. Leak-proof and BPA-free.",
    ratings: 4.7,
    price: 599,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://images.unsplash.com/photo-1664714628878-9d2aa898b9e3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8c3RlZWwlMjB3YXRlciUyMGJvdHRsZXxlbnwwfHwwfHx8MA%3D%3D"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "home & furniters",
  },
  {
    name: "Leather Wallet (Unisex)",
    details: "Slim and stylish wallet made from 100% genuine leather. RFID protection and 8 card slots.",
    ratings: 4.7,
    price: 899,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://images.unsplash.com/photo-1620109176813-e91290f6c795?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGVhdGhlciUyMHdhbGxldHxlbnwwfHwwfHx8MA%3D%3D"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "fashion",
  },
  {
    name: "Minimalist Wall Clock",
    details: "Silent sweep movement, matte finish frame, and clear typography. Perfect for any modern interior.",
    ratings: 4.6,
    price: 1199,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "http://localhost:5000/images/wallclock.jpg"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "home & furniters",
  },
  {
  name: "LEGO City Fire Station Set",
  details: "Buildable playset with fire trucks, fire crew, and detailed station. Ideal for ages 6+ with 500+ pieces.",
  ratings: 4.9,
  price: 3299,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://images.unsplash.com/photo-1579466120767-2f0d36fa7053?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8TEVHTyUyMENpdHklMjBGaXJlJTIwU3RhdGlvbiUyMFNldHxlbnwwfHwwfHx8MA%3D%3D"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "toys"
 },
{
  name: "Remote-Controlled Monster Truck",
  details: "Rechargeable RC vehicle with large tires and shock suspension. 2.4GHz controller included.",
  ratings: 4.7,
  price: 1899,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://media.istockphoto.com/id/1290152789/photo/the-boy-is-controling-the-blue-toy-car-with-a-remote-control-child-play-with-a-toy-car.webp?a=1&b=1&s=612x612&w=0&k=20&c=yvrNcS-sWvxuf_smw6s4vOrfbVUom8ttBEEhosu0eZA="},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "toys"
},
{
  name: "Plush Teddy Bear (XL)",
  details: "Soft cuddle-friendly plush bear, 3 feet tall. Perfect for birthdays and decor.",
  ratings: 4.6,
  price: 749,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.WO7nott69wvWqU4b70G4vQAAAA?w=196&h=196&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "toys"
},
{
  name: "Samsung 6.5kg Top Load Washing Machine",
  details: "Energy-efficient washing with multiple cycles, smart inverter motor, and sleek black finish.",
  ratings: 4.6,
  price: 15290,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.oRnqpMQVYgIEMm6GIPu4pwHaHa?w=181&h=182&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "appliances"
},
{
  name: "Philips Air Fryer XL",
  details: "Healthy frying with rapid air technology. 1.2kg basket, black matte finish, touchscreen controls.",
  ratings: 4.7,
  price: 9990,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.OaqhoaeyoQNsvfvX6u6tswHaHa?w=195&h=195&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "appliances"
},
{
  name: "Haier Double Door Refrigerator (256L)",
  details: "Frost-free fridge with inverter compressor, toughened glass shelves, and LED lighting.",
  ratings: 4.6,
  price: 23999,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.6907EMCEwSmrzHeAkD1KAQAAAA?w=192&h=200&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "appliances"
},
{
  name: "Slim Fit Casual Shirt",
  details: "Cotton-blend men's shirt with roll-up sleeves, button collar, and breathable fabric. Perfect for daily wear.",
  ratings: 4.5,
  price: 899,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.PGU90xMjuYZbTrhqyTxIqwAAAA?w=208&h=208&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "fashion"
},
{
  name: "Women's High-Waist Jeans",
  details: "Stretch denim jeans with tapered cut and reinforced stitching. Flattering silhouette with maximum comfort.",
  ratings: 4.7,
  price: 1299,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.jnlcVQ8YxYwpZlH-Ae21IQHaHa?w=208&h=208&c=7&r=0&o=5&dpr=1.3&pid=1.7"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "fashion"
},
{
  name: "Unisex Black Sneakers",
  details: "Lightweight sneakers with cushioned sole and breathable upper. Stylish for workouts or streetwear.",
  ratings: 4.6,
  price: 1599,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.xzTLTHRhnkJq9pAz-j31nwHaJ4?w=208&h=277&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "fashion"
},
{
  name: "Smart LED TV 43-inch",
  details: "Full HD display with built-in WiFi, OTT apps, and Dolby sound. Sleek bezels and voice remote included.",
  ratings: 4.8,
  price: 23999,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.xIK7rV0DbxzicQrZcCi4bQHaHa?w=166&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "electronics"
},
{
  name: "Dell Inspiron 15 Laptop",
  details: "Intel i5, 8GB RAM, 512GB SSD. Perfect for students and professionals. Includes Windows 11 and MS Office.",
  ratings: 4.7,
  price: 52990,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.BwAUw5opGSXeOJivSuKTygHaHa?w=187&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "electronics"
},
{
  name: "Bluetooth Soundbar with Subwoofer",
  details: "300W output, deep bass, wireless connectivity, and multiple input modes. Enhance your home theater experience.",
  ratings: 4.5,
  price: 6999,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.H8luo2gKEGvMncDSMxdq4gHaHa?w=161&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "electronics"
},
{
  name: "Samsung Galaxy S23",
  details: "Flagship 5G phone with Snapdragon 8 Gen 2, 120Hz AMOLED display, and triple-lens camera setup.",
  ratings: 4.9,
  price: 44999,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.P5Ga8TVqbzBTF914QLUTiAHaFj?w=206&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "mobiles"
},
{
  name: "iPhone 14 Plus",
  details: "6.7-inch Super Retina XDR display, A15 Bionic chip, advanced dual-camera system, and crash detection.",
  ratings: 4.8,
  price: 77990,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.e943jRQHTUQBM4LXS9w6mgHaHa?w=172&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "mobiles"
},
{
  name: "Redmi Note 12 Pro",
  details: "Affordable mid-range beast with 5G, 67W fast charging, AMOLED display, and 50MP OIS camera.",
  ratings: 4.6,
  price: 23999,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.Lr7c-bPMrhDTdqCdJTcYwQHaHa?w=187&h=187&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "mobiles"
},
  {
    name: "XXXFLOWER Plant Terrarium with Wooden Stand",
    details: "Retro-style tabletop decor with 3 bulb glass vases, ideal for showcasing hydroponic plants or flowers.",
    ratings: 4.6,
    price: 899,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://th.bing.com/th/id/OIP.ZaxbWp01LF1zvFRMolj90gHaHa?w=191&h=191&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "home & furniters",
  },
  {
    name: "FRIZZY ARTS Wall Art — Valley of Colors",
    details: "Vibrant digital reprint in a wooden frame. Autumn alpine escape theme perfect for modern and cozy interiors.",
    ratings: 4.7,
    price: 1199,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://th.bing.com/th/id/OIP.2kHR59pGYF-MQdtud7QrSgHaHa?w=157&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "home & furniters",
  },
  {
    name: "Samsung RR23D2H359U 215L Refrigerator",
    details: "5-star rated fridge with advanced cooling, digital inverter, and energy-efficient technology.",
    ratings: 4.6,
    price: 16990,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://th.bing.com/th/id/OIP.6k3VmIOPaXd0N41eJxct1wHaHa?w=165&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "appliances",
  },
{
  name: "Sony WH-1000XM5 Wireless Headphones",
  details: "Industry-leading noise cancellation, 30-hour battery life, touch controls, and ultra-comfortable design. Ideal for work, travel, and immersive audio.",
  ratings: 4.8,
  price: 29990,
  discountType : "percentage",
  discountValue: 20,
  images: [{url: "https://th.bing.com/th/id/OIP.6mxvtD4DVM3J2cxc-ypAgAHaHa?w=180&h=180&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
  stock: 10,
  validUntil: new Date("2025-12-28"),
  catagory: "electronics"
},
  {
    name: "OnePlus Nord CE 3 Lite",
    details: "120Hz IPS display, Snapdragon 695 processor, 108MP camera, and 67W fast charging. Value-packed midrange.",
    ratings: 4.7,
    price: 19999,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://th.bing.com/th/id/OIP.SUoRz5czlGHZG5-Gx7uNcQHaHa?w=189&h=190&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "mobiles",
  },
  {
    name: "Magnetic Building Tiles (100 pcs)",
    details: "Educational toy for kids aged 3+, promotes creativity and spatial thinking. Safe and durable plastic.",
    ratings: 4.6,
    price: 1599,
    discountType : "percentage",
    discountValue: 20,
    images: [{url: "https://th.bing.com/th/id/OIP.84mX9I_YTs4nRVycdgSr6QHaHa?w=198&h=198&c=7&r=0&o=7&dpr=1.3&pid=1.7&rm=3"},{url: "http://localhost:5000/images/heroimage1.jpg"},{url: "http://localhost:5000/images/heroimage2.jpg"},{url: "http://localhost:5000/images/heroimage3.jpg"},{url: "http://localhost:5000/images/heroimage4.jpg"},{url: "http://localhost:5000/images/heroimage5.jpg"}],
    stock: 10,
    validUntil: new Date("2025-12-28"),
    catagory: "toys",
  },
];

module.exports = { data : products };